### ISSUE TITLE
Add custom color for active state of burger menu

### ISSUE THREAD

**Issue by dkoether** [solitweb/full-screen-menu-for-elementor#2]
Hello,

I think it would be a good improvment to have to possibility to set a color for the following case:

E.g. if you change from a white header with green icon to a same color green overlay then the burger menu icon (menu opener) is invisible cause you cannot set a color for the close icon over the menu overlay:

Inactive:
![grafik](https://user-images.githubusercontent.com/7765498/114593016-e3baf600-9c8b-11eb-9e04-505fca7e5401.png)

Active (only visible because of the hover color):
![grafik](https://user-images.githubusercontent.com/7765498/114593055-f5040280-9c8b-11eb-876b-ccb4add491f5.png)

What do you think?

Keep up the good work and thanks in advance for this good wordpress plugin!

**Comment by stijnvanouplines** [comment]
You can always achieve this with custom CSS. If you think something is missing, a PR is always welcome!
