### ISSUE TITLE
Prevent scrolling while menu overlay is open

### ISSUE THREAD

**Issue by dkoether** [solitweb/full-screen-menu-for-elementor#3]
Hello,

a big UX improvement would be if the user cannot scroll while the menu overlay is open. Otherwise the closing "X" scrolls out of area, because it is absolute in its position.

What do you think?

Thanks in advance!

**Comment by stijnvanouplines** [comment]
To achieve this you need JavaScript. The make this plugin is as lightweight as possible we used no JavaScript.
